language: node_js
node_js:
- 8.9.4
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run chrome
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "${GH_TOKEN}"
  keep-history: true
  local-dir: public
  on:
    branch: master
env:
  global:
  - secure: B33mAP02j701d7LV6DC4dlvGctPfLago0KqE4LytPKVHqAD1AAtwBa7OvdWiJVXCRkD95xdOwqNkycqQqVBC1AT15/Lqvq4o4NHVnGtNc8BswU3M5OXYOu5NEi51/8uTVVz6BrXLuCAAvVA+z14+WGPWVTWvgnnn3duvEITCGUIjjWO/0JWZLUICuwIkwfPjC8Ah+WSsxSpHC6ceUkoqm7Y0nVQWf43kWa4yIH9iBadnIe/DKoT617xMKBIPkms4gU+zUWYarik5eN3JEKTXpkuRrDC/u8GDDHX1WxfHU4DqDJmo2/iFaOFMLHo+7AGrC6L3m0jq/ytdmSWNleGcsspRd/prBiN8przzCpcL12jIX5m3ewzXZ+IOeurihiOsXqmglz/LzW+gXTUUWPDzR8Q2IgVSimlptszuNLa9T8JEqr+EyV0ay9Ugpwh26oGCrSMqugOTzYm2mcIarECbktx6O+dpZCscsqn6qk1WVJj2Vl9LiZK3JZMlTy7aThYle0MJ9hacXHdDvxZQ1/N8BtYf0UH4oHdxQerAdWRzcnWa6KH1YZlNOOGHOEiosvrS/0vPyrRHYqad4vwDatPGhDcLoq9RhUms9VLeuQnYvAXVSVixs3zLiEwE+e5RHnRx3oQx/vJNry6Ale3mB23BvcaWoJdic6uOs/pWwtr7tKw=
